apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: applications.operators.pyhp2017.github.io
spec:
  group: operators.pyhp2017.github.io
  scope: Namespaced # resources can be namespaced or available for the whole cluster
  names:
    kind: Application
    plural: applications
    shortNames:
      - app
    singular: application

  versions:
    - name: v1
      served: true #enabled/disabled
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                image:
                  type: string
                tag:
                  type: string
                port:
                  type: integer
                replicas:
                  type: integer
